---
- hosts: 172.31.10.229 
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: create a folder 
    file:
      path: /home/maha/myfolder
      state: directory
  - name: i want to install apache2 
    apt:
      name: apache2
      state: present
  - name: i want to copy a file into node side
    copy:
       src: mytestfile
       dest: /home/maha/myfolder

  - name: i want to download internet file 
    get_url:
     url: https://updates.jenkins.io/download/war/2.509/jenkins.war
     dest: /home/maha/myfolder/jenkins.war
     force_basic_auth: yes

  - name: how to copy index file into nodes 
    template:
         src: myindex.j2
         dest: /var/www/html/index.html