---
- hosts: 172.31.10.229 
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: create a folder 
    file:
      path: /home/maha/myfolder
      state: directory
  - name: i want to install apache2 
    apt:
      name: apache2
      state: present

